### ISSUE TITLE
Markers are  2 to 8 seconds early. Not entirely accurate

### ISSUE THREAD

**Issue by BeverlyLaurelBLVD** [Aimarekin/Aimarekins-Spicetify-Extensions#11]
As title describes. It seems the markers range from 2 to 8 seconds too early in the timeline of the track vs where the next section of a song actually begings.

As a music producer this spicetify extension is actually an amazing idea to look at song-structure, just needs some small, but important fixes... and it's perfect.

**Comment by BeverlyLaurelBLVD** [comment]
Follow up, some markers are late as well. Especially for sections that are overtly different. 

Example::: Passionfruit by Drake: The quiet beginning and then when the drums come in. The marker is late.

**Comment by QazCetelic** [comment]
I also noticed this issue with several songs, but it seems like the data is just pulled from [Spotify's API](https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis). So, it's a problem with Spotify's analysis instead of a problem with the plugin itself.

**Comment by Aimarekin** [comment]
Sections are provided by Spotify's analysis API as pointed out by @QazCetelic. Not a bug nor something that I could change. I'm looking on other possible sources for more accurately representing a song's sections
