### ISSUE TITLE
Section marker seems to no longer function

### ISSUE THREAD

**Issue by DrekAnon** [Aimarekin/Aimarekins-Spicetify-Extensions#14]
Manual installation and marketplace installation of the plugin seem to have no changes towards the seekbar. Even when reloading manually.

**Comment by Aimarekin** [comment]
> Manual currently does not work

Correction: The file in _dist is the live version, but the source code doesn't match. Manual installation should work the same as marketplace.

**Comment by Aimarekin** [comment]
Can't reproduce - extension installed through marketplace on Spotify version 1.2.43.420 and Spicetify 2.37.1 works fine for me. How have you installed the extension @DrekAnon?

**Comment by MintMarbles** [comment]
Mine stopped working today as well
I tried updating spicetify and it didn't do anything
Tried downloading/reloading extension, didn't do anything.

DJ info also stopped working for me at the same time :((((((

Spotify for Windows (32 bit)
1.2.22.982.g794acc0a
Spicetify v2.28.1

**Comment by MintMarbles** [comment]
Working again for me, I think spotify is just a mess today

**Comment by Aimarekin** [comment]
Good to hear, make sure to follow the guide when updating Spotify 
https://spicetify.app/docs/getting-started/#updating
