### ISSUE TITLE
[Feature Request] Different Section Markers' markers

### ISSUE THREAD

**Issue by Satanarious** [Aimarekin/Aimarekins-Spicetify-Extensions#5]
Couple of Section Marker icons/markers for start and end indicators, something like this:
- Different lengths for start and end(obviously for themes where progress-bar height is the original or close):
![Screenshot 2023-07-05 010959](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/42642682/16b56b81-b402-4c29-b6e4-270fa53a6682)
- Or, Completely different icons/colours for start and end(Maybe have this override for themes):
![Screenshot 2023-07-05 011645](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/42642682/786d521e-3072-4b81-9408-8a996e7c5527)
- Or, keep 2nd option with marker height the same size as the progress-bar height.

**Comment by Aimarekin** [comment]
The whole track is covered by sections - certain parts of the bar being darkened doesn't mean that's a section and the rest isn't, it's just an even/odd coloring to tell them apart more easily (and make it more pleasing).

Everywhere a section ends another begins, and the markers signify where the sections change.

**Comment by Satanarious** [comment]
Oh! didn't know that.
Then how about the 3rd option? Marker height same as the progress-bar height but with a different colour that overrides themes

**Comment by Aimarekin** [comment]
> Marker height same as the progress-bar height but with a different colour that overrides themes

I don't think I understand - the markers do not signify the start and end of a section, rather where they change, so it wouldn't make much sense to color them differently other than for aesthetic purposes, they are just a separator. The odd/even coloring on the bar is enough to portray all the necessary information.

Next update there will be an option to hide the markers in the settings.

**Comment by Satanarious** [comment]
I mean a different colour in a sense to not match the progress-bar colour, like in option 1. I guess this is due to the theme. Making the markers the same height as the progress-bar will hide the markers which would be past the current progress since they are the same colour. I mean this:

![Screenshot 2023-07-05 011645](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/42642682/9e47d5ef-cf85-4306-8053-e3e2c1578f77)

Makes it look more blended IMO.

**Comment by Aimarekin** [comment]
I feel like this should be left up to the individual theme and snippet developers to implement - the current solution tries to be compatible and universal.

Splitting up the bar by overlaying markers with a background isn't possible with all themes as in some the background may be translucent or have more complex styling we'd need a more elaborate solution for.

In thinner bars, such as sidebar controls', I feel like this solution would not be very elegant.

Developers can apply their own CSS rules to the elements, and will have information about the overall look of the bar we do not as an extension (or would need a very complex system to know) they can use to adapt the extension to their needs.

**Comment by Satanarious** [comment]
Totally understandable. I was wondering if you could maybe provide me with a CSS snippet to have the bars the same height as the progress bar in black colour?

**Comment by Aimarekin** [comment]
> Totally understandable. I was wondering if you could maybe provide me with a CSS snippet to have the bars the same height as the progress bar in black colour?

With the latest update 1.1.0, this snippet should work:
```css
.section-marker-sections {
    display: none;
}
.section-marker-markers {
    display: block !important; /* So as to never have them hidden, regardless of the bar's width */
}
.section-marker-marker {
    height: 100%; /* For 1.0.0, instead use var(--progress-bar-height) */
    background-color: var(--spice-player);
}
```
