### ISSUE TITLE
Incompatibility with the extension `beautiful-lyrics`

### ISSUE THREAD

**Issue by TheMayhem6328** [Aimarekin/Aimarekins-Spicetify-Extensions#7]
When using [section-marker](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/tree/main/section-marker) in conjunction to [beautiful-lyrics](https://github.com/surfbryce/beautiful-lyrics), this is noticed. Basically, in the latter extension's `cinematic mode`, the progress bar is supposed to dim out, but it isn't happening:

![Image of bar not dimming out](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/56154436/bbbe22fe-84e5-4dec-ba37-6c487c492874)

If this helps, I'm using Spotify on Windows with Spotify for Windows (64 bit) with Spicetify v2.23.0, and have been using marketplace for extensions. I'm using [the `bloom` theme](https://github.com/nimsandu/spicetify-bloom)

**Comment by Aimarekin** [comment]
Thanks for the report - Are you sure this is an issue with section marker? The applied styling should only slightly darken the bar with an overlay and does not modify it's overall opacity - I think it might be the theme changing it.

**Comment by Aimarekin** [comment]
No response - assuming this is not a bug
