### ISSUE TITLE
Can't select individual tracks for skipping

### ISSUE THREAD

**Issue by horizon1g** [Aimarekin/Aimarekins-Spicetify-Extensions#8]
Not sure if this is event meant to be a thing but in the gif preview on the spicetify discord it looks like it changes on the track switch

Basically its changing the timestamp to skip for every track i play and not an individual one i added the timestamp to, and in spotify's settings i can't seem to find settings for this extension.

**Comment by Aimarekin** [comment]
This is intended. The timestamp to skip on does not change - it is an absolute value. However as tracks have different lengths, the marker will move accordingly to represent where that timestamp is on the bar relative to the track's length.

You can switch to percentage mode to skip based on percentages instead - in this case the marker will never move as relative to the songs length it is always in the same position.
