### ISSUE TITLE
Playing Source shows CURRENTLY PLAYING on everything

### ISSUE THREAD

**Issue by Tequinzyy** [Aimarekin/Aimarekins-Spicetify-Extensions#9]
![image](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/116754124/1b821e07-298e-4b72-9ac9-66404f7649de)

**Comment by Aimarekin** [comment]
Playing Source is currently legacy and does not work (and isn't adapted to) current Spotify versions, won't be fixed. A modern version of the extension with the new Now Playing interface is planned
